#!/bin/bash
#
# Il faut changer IAP en IAP pour dérouler ce script sur la prod
#

if [ ! -f /opt/apps/iv-patch-records/conf/conf.inc ]; then
	echo "Un fichier /opt/apps/iv-patch-records/conf/conf.inc est nécessaire (c'est écrit dans le MD de livraison pourtant)"
	exit 1 
fi
source /opt/apps/iv-patch-records/conf/conf.inc
source /opt/apps/iv-patch-records/commons

fichier=$1
if [[ "$DEST_DIR" == "" ]]; then
	echo "Le répertoire de destination des mp3 n'est pas précisé dans le fichier /opt/apps/iv-patch-records/conf/conf.inc (DEST_DIR)"
	exit 1
fi
USAGE="""Usage : iv-move-records FICHIER_MP3
	FICHIER_MP3 : Comment dire ... J'intuite qu'il s'agit d'un fichier mp3.	
	Alors, ça prend ce fichier, ça déduit l'id dans la base IAP, ça retrouve les infos dans base IAP, ça pousse le fichier vers le stockage et ça met à jour les infos dans la base IAP. Et ça supprime le fichier localement. Attention ! Je l'ai dit, c'est écrit.
"""

if [[ "$fichier" == "" ]]; then
	echo -e "$USAGE"
	exit 1
fi
name=$(basename $fichier)
vocal_record_id=$(python -c "from hashids import Hashids;h=Hashids(salt='recordsapi hashids salt tartiflette', min_length = 8);print(h.decrypt('${name%.*}')[0]);")
read projet whitelabel queue stop_date < <(sql_query "select p.project, p.whitelabel, vq.name, substr(vr.stop_time,1,10) from ( select project_ref, vocal_queue_ref, stop_time from VocalRecords where id=$vocal_record_id ) vr inner join Projects p on p.id = vr.project_ref inner join VocalQueues vq on vq.id = vr.vocal_queue_ref;" IAP)
mkdir -p $DEST_DIR/$whitelabel/$projet/$stop_date/$queue
if [[ "$?" != "0" ]];then 
	log "ERREUR : Impossible de créer le dossier $DEST_DIR/$whitelabel/$projet/$stop_date/$queue"
	exit 1
fi
destination=$DEST_DIR/$whitelabel/$projet/$stop_date/$queue/$name

cp $fichier $destination
if [[ "$?" != "0" ]];then
	log "ERREUR : Impossible de copier $fichier vers $destination"
	exit 1
fi

rm -f $fichier
if [[ "$?" != "0" ]];then
	log "WARNING : Le fichier temporaire $fichier n'a pas pu être effacé"
fi


