#!/bin/bash
# Version: 1.0
# Auteurs: GETOUMI, DANTON & POPOTIN
USAGE='Usage: ccr PROJET "users|sessions" FIELDS [SERVEUR]
	Simplifie l''usage  de ccenter_report pour interroger un process dispatch d''un projet
	'
if [[ "$1" == "-h" ]]
then
	echo -e "$USAGE"
	exit 1
fi

if [ $# -lt 3 ]; then
	echo -e "$USAGE"
	exit 2
fi
projet=$1
racine=$2
champs=$3
serveur=$4
[[ "$serveur" == "" ]] && serveur="localhost"   # Syntaxe une ligne de if then fi 

function ccc_processes {
	ccenter_update -login admin -password admin -server $serveur 20000 -children /proc/consistent_1/Head_Main/Head_$projet               
}
function ccc_process {
	ccenter_update -login admin -password admin -server $serveur 20000 -content /proc/consistent_1/Head_Main/Head_$projet/$1
}


if [[ $(ccc_processes | grep "Dispatch|") == "" ]]; then
        echo "ERREUR : Process Dispatch pour le projet $projet non trouvé sur le serveur $serveur"
        exit 3
fi

port=$(ccc_process Dispatch | grep -oPm1 "(?<= port=\")[^\"]+");

[[ "${champs: -1}" == ";" ]] && champs=$(echo $champs | sed 's/.$//g')  # On retire le dernier ';' s'il y en a un.

entetes=$(echo $champs | sed 's/;/|/g')
entetes=$(echo $entetes | sed 's/\.v//g')   # Abrégé : .v -> [rien] 
#entetes=$(echo $entetes | sed "s/\.c/.count/g")   # Abrégé : .c -> .count
#entetes=$(echo $entetes | sed "s/\.d/.durat/g")   # Abrégé : .d -> .duration
#entetes=$(echo $entetes | sed "s/\.m/.max/g")   # Abrégé : .d -> .duration

champs=row.$(echo $champs | sed 's/;/;row./g')   # On rajoute l'inutile "row." devant chaque champs (sans oublier le premier)
champs=$(echo $champs | sed 's/\.v/.value/g')   # Abrégé : .v -> .value
champs=$(echo $champs | sed "s/\.c/.count('0')/g")   # Abrégé : .c -> .count('0')
champs=$(echo $champs | sed "s/\.d/.duration('0')/g")   # Abrégé : .d -> .duration('0')
champs=$(echo $champs | sed "s/\.m/.max('0')/g")   
{ echo $entetes; ccenter_report -login admin -password admin -server $serveur $port -path /dispatch_$projet -list -field $racine -fields "$champs"; } | column -t -s"|"
