#!/bin/bash
# Version: 1.0
# Auteur: GETOUMI
USAGE='Usage: iv-add-cdr PROJET [HOSTNAME] 
	Ajoute un process CDR au projet PROJET sur le serveur consistent HOSTNAME (localhost par défaut).
	Note : le binaire ccenter_cdr doit avoir été déployé sur le serveur consistent. 
	'
if [[ "$1" == "-h" ]]
then
	echo -e "$USAGE"
	exit 1
fi

if [ $# -ne 2 ] && [ $# -ne 1 ]; then
	echo -e "$USAGE"
	exit 2
fi

if [ $# -eq 1 ]; then
	serveur=localhost
else
	serveur=$2
fi
projet=$1

function ccc_projects { 
	ccenter_update -login admin -password admin -server $serveur 20000 -children /db/projects                 
}

if [[ $(ccc_projects | grep "$projet|") == "" ]]; then
	echo "ERREUR : Projet $projet non trouvé sur le serveur $serveur"
	exit 3
fi

# Génération du contenu adéquate dans un fichier temporaire
fichier=$(mktemp)
cat << EOF > $fichier
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<com.consistent.head.consistent_stand_alone_process id="_1" class_name="cdr" process_name="ccenter_cdr" max_stop_duration="0" max_respawn_count="1" max_respawn_duration="0" retry_interval="5" big_retry_interval="0" active="1" scheduling_policy="0" scheduling_priority="0" lock_memory="0" kill_number="0">
	<arguments>
		<consistent_process_argument id="_2" value="$projet"/>
	 </arguments>
 </com.consistent.head.consistent_stand_alone_process>
EOF

# Pis on l'ajoute sur le serveur consistent 
cdr_path=/db/projects/$projet/processes/consistent_1/Head_Main/Head_$projet/Cdr
ccenter_update -login admin -password admin -server $serveur 20000 -children $cdr_path 2> /dev/null 1> /dev/null
if [[ "$?" != "0" ]]
then
	ccenter_update -login admin -password admin -server $serveur 20000 -mknode $cdr_path
fi
ccenter_update -login admin -password admin -server $serveur 20000 -path $cdr_path -file $fichier

rm $fichier
