#!/bin/bash
# Version: 1.0
# Auteur: GETOUMI
USAGE='Usage: iv-upgrade-outbound HOSTNAME PROJET 
	Migre la configuration applicative d'\''un projet (  fichiers Ccxml.xml et Queues.xml ) 
	Effectue une copie avant modification des fichiers ( Ccxml.xml.DATE.HEURE et Queues.xml.DATE.HEURE )
	'
if [[ "$1" == "-h" ]]
then
	echo -e "$USAGE"
	exit 1
fi

if [ $# -ne 2 ]; then
	echo -e "$USAGE"
	exit 2
fi
serveur=$1
projet=$2
maintenant=$(date +'%Y%m%d.%H%M%S')
function ccc_fichiers { 
	ccenter_update -login admin -password admin -server $serveur 20000 -children /db/projects/$projet         
}
function ccc_projects { 
	ccenter_update -login admin -password admin -server $serveur 20000 -children /db/projects                 
}
function ccc_cat { 
	ccenter_update -login admin -password admin -server $serveur 20000 -content /db/projects/$projet/$1       
}
function ccc_put { 
	ccenter_update -login admin -password admin -server $serveur 20000 -path /db/projects/$projet/$1 -file $2 -create
}

if [[ $(ccc_projects | grep "$projet|") == "" ]]; then
	echo "ERREUR : Projet $projet non trouvé sur le serveur $serveur"
	exit 3
fi

if [[ $(ccc_fichiers | grep Queues.xml) == "" ]]; then 
	echo "ERREUR : Fichier Queues.xml non trouvé dans le projet $projet sur le serveur $serveur"
	exit 4
fi

if [[ $(ccc_cat Queues.xml | grep " name=\"outbound\" display_name=\"appels sortants\"") == "" ]];then
	fichier=$(mktemp)
	ccc_cat Queues.xml > $fichier
	ccc_put Queues.xml.$maintenant $fichier
	sed -i -e 's/<\/tasks>/<ccenter_queues_task id="_63567377" name="outbound" display_name="appels sortants"\/><\/tasks>/g' $fichier
	ccc_put Queues.xml $fichier
	rm $fichier
	echo "INFO : Fichier Queues.xml vient d'être upgradé en outbound-transfer après sauvegarde dans Queues.xml.$maintenant"
else
	echo "INFO : Fichier Queues.xml déjà upgradé en outbound-transfer"
fi

if [[ $(ccc_fichiers | grep Ccxml.xml) == "" ]]; then 
	echo "ERREUR : Fichier Ccxml.xml non trouvé dans le projet $projet sur le serveur $serveur"
	exit 4
fi

if [[ $(ccc_cat Ccxml.xml | grep " name=\"agent_outbound\" scenario=\"Outbound.xml\"") == "" ]];then
	fichier=$(mktemp)
	ccc_cat Ccxml.xml > $fichier
	ccc_put Ccxml.xml.$maintenant $fichier
	sed -i -e 's#<entrys>#<entrys><ccenter_ccxml_entry id="_4012070010" name="agent_outbound" scenario="Outbound.xml" disconnected_timeout="0"><values><com.consistent.protocol.consistent_protocol_named_object_value_string id="_4012070011" name="accueil" value="sda_default.xml"/><com.consistent.protocol.consistent_protocol_named_object_value_string id="_4012070012" name="project_type_cfg" value="outbound"/><com.consistent.protocol.consistent_protocol_named_object_value_string id="_4012070013" name="delay_cfg" value="0"/></values></ccenter_ccxml_entry>#g' $fichier
	ccc_put Ccxml.xml $fichier
	rm $fichier
	echo "INFO : Fichier Ccxml.xml vient d'être upgradé en outbound-transfer après sauvegarde dans Ccxml.xml.$maintenant"
else
	echo "INFO : Fichier Ccxml.xml déjà upgradé en outbound-transfer"
fi

echo "INFO : Bon ben j'ai fini mais faut pas oublier de régénérer le callcenter avec le webadmin pour que les profiles soient upgradés"

