module call_control
	{
	interface to
		{
		void call_control_initialize(in uint_32 client_version, in string process_id, in boolean proxy_call) ;
		void call_control_add_session(in string call_id, in string entry_point_name, in string remote_name, in string remote_address, in string remote_contact, in string local_name, in string local_address, in string aai, in date call_creation_date, in boolean hidden_number, in string for_session_id, in object protocol:consistent_protocol_named_object invite_fields) ;
		void call_control_status(in string call_id, in string status, in string info, in uint_32 code) ;
		void call_control_consistent_joined(in string ccxml_id, in string id_1, in string id_2, in boolean duplex) ;
		void call_control_consistent_unjoined(in string ccxml_id, in string id_1, in string id_2) ;
		void call_control_joined(in string ccxml_id, in string id_1, in string id_2) ;
		void call_control_join_failed(in string ccxml_id, in string id_1, in string id_2, in string reason) ;
		void call_control_unjoined(in string ccxml_id, in string id_1, in string id_2) ;
		void call_control_unjoin_failed(in string ccxml_id, in string id_1, in string id_2, in string reason) ;
		void call_control_input_started(in string dialog_id, in uint_32 step_id) ;
		void call_control_input_complete(in string dialog_id, in uint_32 step_id, in uint_32 result, in object w3c_nlsm:w3c_nlsm_result data, in real record_duration, in string error_message) ;
		void call_control_throw_error(in string dialog_id, in string error, in string error_message, in uint_32 status) ;
		void call_control_throw_event(in string ccxml_id, in string call_id, in string event, in object protocol:consistent_protocol_named_object object) ;
		void call_control_conference_created(in string ccxml_id, in string conference_id) ;
		void call_control_conference_destroyed(in string ccxml_id, in string conference_id) ;
		void call_control_call_error(in string call_id, in string error_message) ;
		void call_control_move_result(in string ccxml_id, in string call_id, in uint_32 instance_id, in string error_message) ;
		void call_control_record_started(in string call_id, in string uri) ;
		void call_control_record_stopped(in string call_id) ;
		} ;
	interface from
		{
		void call_control_connection_ok(in uint_32 server_version) ;
		void call_control_accept(in string call_id, in string ccxml_id) ;
		void call_control_incoming_status(in string call_id, in string reason) ;
		void call_control_reject(in string call_id, in string reason) ;
		void call_control_call_entry_not_found(in string call_id) ;
		void call_control_call_not_ready(in string call_id) ;
		void call_control_disconnect(in string call_id) ;
		void call_control_create_call(in string ccxml_id, in string call_id, in string remote_name, in string remote_address, in string remote_contact, in string local_name, in string local_address, in string aai, in real max_ringing_delay, in string join_id, in uint_32 join_direction, in string intended_call_id, in date call_creation_date, in boolean hide_caller, in string stat_name, in object protocol:consistent_protocol_named_object extra_invite_fields) ;
		void call_control_move_call(in string ccxml_id, in string call_id, in uint_32 instance_id, in string intended_call_id) ;
		void call_control_record(in string call_id, in string mode, in string type, in string compression, in string uri, in boolean append) ;
		void call_control_stop_record(in string call_id) ;
		void call_control_detect_tones(in string call_id, in boolean fax, in boolean frequencies, in real min_detection_duration, in real duration) ;
		void call_control_add_dialog(in string ccxml_id, in string dialog_id, in uint_32 rtp_timeout, in string call_id) ;
		void call_control_remove_dialog(in string dialog_id) ;
		void call_control_join(in string ccxml_id, in string id_1, in string id_2, in uint_32 join_direction, in boolean dtmf_clamp, in uint_32 mode) ;
		void call_control_unjoin(in string ccxml_id, in string id_1, in string id_2) ;
		void call_control_remove_grammars(in string dialog_id, in uint_32 scope) ;
		void call_control_add_external_grammar(in string dialog_id, in uint_32 grammar_id, in string uri, in string type, in uint_32 scope, in real fetch_timeout, in real grammar_max_age, in real grammar_max_stale, in boolean is_dtmf, in string content_base) ;
		void call_control_add_pcdata_grammar(in string dialog_id, in uint_32 grammar_id, in string grammar, in string type, in uint_32 scope, in string content_base) ;
		void call_control_add_inline_grammar(in string dialog_id, in uint_32 grammar_id, in object w3c_grammar:w3c_grammar grammar, in string type, in uint_32 scope, in boolean optional, in string content_base) ;
		void call_control_record_dialog(in string dialog_id, in object ccenter_call_control:ccenter_call_control_record record) ;
		void call_control_set_asr_values(in string dialog_id, in object protocol:consistent_protocol_named_object asr_values) ;
		void call_control_execute_prompts_and_input(in string dialog_id, in object ccenter_call_control:ccenter_call_control_prompt prompt, in uint_32 step_id, in boolean modal, in uint_32 term_char, in real no_input_delay, in real interdigit_delay, in real term_char_delay, in real speech_complete_delay, in real speech_incomplete_delay, in real max_speech_delay, in real confidence_level, in real sensitivity, in real speed_vs_accuracy, in uint_32 max_n_best, in uint_32 input_modes) ;
		void call_control_define_fetch_policy(in string dialog_id, in string file_name, in real delay, in real minimum, in real timeout) ;
		void call_control_create_conference(in string ccxml_id, in string conference_id, in string intended_call_id) ;
		void call_control_destroy_conference(in string ccxml_id, in string conference_id) ;
		void call_control_add_registred(in string ccxml_id, in string sip_id) ;
		void call_control_remove_registred(in string ccxml_id, in string sip_id) ;
		} ;
	} ;

module inter_call_control
	{
	interface to
		{
		void inter_call_control_initialize(in uint_32 client_version, in string process_id) ;
		void inter_call_control_create_call(in string call_id, in string stat_name, in string ccxml_id, in string remote_address, in uint_16 old_port) ;
		void inter_call_control_delete_call(in string call_id) ;
		void inter_call_control_stop_call(in string call_id) ;
		void inter_call_control_set_remote_rtp(in string call_id, in uint_32 rtp_payload, in uint_32 rtp_address, in uint_32 rtp_port, in uint_32 dtmf_payload, in boolean use_first_packet_address) ;
		void inter_call_control_record(in string call_id, in string mode, in string type, in string compression, in string uri, in boolean append) ;
		void inter_call_control_stop_record(in string call_id) ;
		void inter_call_control_detect_tones(in string call_id, in boolean fax, in boolean frequencies, in real min_detection_duration, in real duration) ;
		void inter_call_control_add_dialog(in string ccxml_id, in string dialog_id, in uint_32 rtp_timeout, in string call_id) ;
		void inter_call_control_remove_dialog(in string dialog_id) ;
		void inter_call_control_join(in string ccxml_id, in string id_1, in string id_2, in uint_32 join_direction, in boolean dtmf_clamp, in uint_32 mode) ;
		void inter_call_control_unjoin(in string ccxml_id, in string id_1, in string id_2) ;
		void inter_call_control_remove_grammars(in string dialog_id, in uint_32 scope) ;
		void inter_call_control_add_external_grammar(in string dialog_id, in uint_32 grammar_id, in string uri, in string type, in uint_32 scope, in real fetch_timeout, in real grammar_max_age, in real grammar_max_stale, in boolean is_dtmf, in string content_base) ;
		void inter_call_control_add_pcdata_grammar(in string dialog_id, in uint_32 grammar_id, in string grammar, in string type, in uint_32 scope, in string content_base) ;
		void inter_call_control_add_inline_grammar(in string dialog_id, in uint_32 grammar_id, in object w3c_grammar:w3c_grammar grammar, in string type, in uint_32 scope, in boolean optional, in string content_base) ;
		void inter_call_control_record_dialog(in string dialog_id, in object ccenter_call_control:ccenter_call_control_record record) ;
		void inter_call_control_set_asr_values(in string dialog_id, in object protocol:consistent_protocol_named_object asr_values) ;
		void inter_call_control_execute_prompts_and_input(in string dialog_id, in object ccenter_call_control:ccenter_call_control_prompt prompt, in uint_32 step_id, in boolean modal, in uint_32 term_char, in real no_input_delay, in real interdigit_delay, in real term_char_delay, in real speech_complete_delay, in real speech_incomplete_delay, in real max_speech_delay, in real confidence_level, in real sensitivity, in real speed_vs_accuracy, in uint_32 max_n_best, in uint_32 input_modes) ;
		void inter_call_control_define_fetch_policy(in string dialog_id, in string file_name, in real delay, in real minimum, in real timeout) ;
		void inter_call_control_create_conference(in string ccxml_id, in string conference_id) ;
		void inter_call_control_destroy_conference(in string ccxml_id, in string conference_id) ;
		} ;
	interface from
		{
		void inter_call_control_connection_ok(in uint_32 server_version) ;
		void inter_call_control_max_calls_count(in uint_32 count) ;
		void inter_call_control_current_calls_count(in uint_32 count) ;
		void inter_call_control_create_call_failed(in string call_id) ;
		void inter_call_control_create_call_result(in string call_id, in string rtp_address, in uint_32 rtp_port) ;
		void inter_call_control_disconnect(in string call_id) ;
		void inter_call_control_consistent_joined(in string ccxml_id, in string id_1, in string id_2, in boolean duplex) ;
		void inter_call_control_consistent_unjoined(in string ccxml_id, in string id_1, in string id_2) ;
		void inter_call_control_joined(in string ccxml_id, in string id_1, in string id_2) ;
		void inter_call_control_join_failed(in string ccxml_id, in string id_1, in string id_2, in string reason) ;
		void inter_call_control_unjoined(in string ccxml_id, in string id_1, in string id_2) ;
		void inter_call_control_unjoin_failed(in string ccxml_id, in string id_1, in string id_2, in string reason) ;
		void inter_call_control_input_started(in string dialog_id, in uint_32 step_id) ;
		void inter_call_control_input_complete(in string dialog_id, in uint_32 step_id, in uint_32 result, in object w3c_nlsm:w3c_nlsm_result data, in real record_duration, in string error_message) ;
		void inter_call_control_throw_error(in string dialog_id, in string error, in string error_message, in uint_32 status) ;
		void inter_call_control_throw_event(in string ccxml_id, in string call_id, in string event, in object protocol:consistent_protocol_named_object object) ;
		void inter_call_control_conference_created(in string ccxml_id, in string conference_id) ;
		void inter_call_control_conference_destroyed(in string ccxml_id, in string conference_id) ;
		void inter_call_control_call_error(in string call_id, in string error_message) ;
		} ;
	} ;

module tts_control
	{
	interface to
		{
		void tts_control_initialize(in uint_32 client_version) ;
		void tts_control_generate(in uint_32 system_id, in object w3c_ssml:w3c_ssml_speak speak) ;
		void tts_control_stop(in uint_32 system_id) ;
		} ;
	interface from
		{
		void tts_control_connection_ok(in uint_32 server_version) ;
		void tts_control_start_data(in uint_32 system_id, in uint_32 format) ;
		void tts_control_add_data(in uint_32 system_id, in data data), debug=false ;
		void tts_control_end_data(in uint_32 system_id) ;
		} ;
	} ;

module queues
	{
	interface to
		{
		void queues_initialize(in uint_32 client_version, in string server_name) ;
		void queues_user_lock(in string user_id, in uint_32 priority) ;
		void queues_user_set_lock_priority(in string user_id, in uint_32 priority) ;
		void queues_user_unlock(in string user_id) ;
		void queues_session_add(in uint_32 client_index, in string session_id, in string user_id, in date event_date, in string state_name, in object ccenter_queues:ccenter_queues_user_state state, in uint_32 instances_count, in string display_name) ;
		void queues_session_remove(in uint_32 client_index) ;
		void queues_session_set_instances_count(in uint_32 client_index, in date event_date, in uint_32 instances_count) ;
		void queues_session_add_extra_service(in uint_32 client_index, in string service, in real priority, in real skill, in uint_32 min_absolute_priority, in boolean manually) ;
		void queues_session_remove_extra_service(in uint_32 client_index, in string service) ;
		void queues_session_update_queues(in uint_32 client_index, in object ccenter_queues:ccenter_queues_user_state state, in date state_date, in string state_name) ;
		void queues_session_task_lock(in uint_32 client_index, in uint_32 session_instance_id, in date event_date, in uint_32 user_task_id) ;
		void queues_session_task_manage(in uint_32 client_index, in uint_32 session_instance_id, in date event_date, in uint_32 user_task_id) ;
		void queues_session_task_management_effective(in uint_32 client_index, in uint_32 session_instance_id, in date event_date, in uint_32 user_task_id) ;
		void queues_session_task_post_managing(in uint_32 client_index, in uint_32 session_instance_id, in date event_date, in uint_32 user_task_id) ;
		void queues_session_task_managed(in uint_32 client_index, in uint_32 session_instance_id, in date event_date, in uint_32 user_task_id, in string reason, in object protocol:consistent_protocol_named_object object, in real temporization) ;
		void queues_session_task_failed(in uint_32 client_index, in uint_32 session_instance_id, in date event_date, in uint_32 user_task_id, in string task_name, in real timeout, in string reason) ;
		void queues_session_task_transfer(in uint_32 client_index, in uint_32 session_instance_id, in date event_date, in uint_32 user_task_id, in string new_manager_id, in real temporization, in string remote_session_id, in uint_32 remote_user_task_id) ;
		void queues_session_task_event(in uint_32 client_index, in string task_id, in string source, in real delay, in string event_name, in object protocol:consistent_protocol_named_object object) ;
		void queues_session_task_recover(in uint_32 client_index, in uint_32 session_instance_id, in uint_32 user_task_id, in string task_name, in string task_id, in string queue_name, in uint_32 management_state) ;
		void queues_session_task_create(in uint_32 client_index, in uint_32 session_instance_id, in uint_32 user_task_id, in string task_name) ;
		void queues_task_add(in string session_id, in string object_id, in string task_id, in string queue_type, in string queue_name, in string task_name, in date waiting_date, in real priority, in uint_32 absolute_priority, in object protocol:consistent_protocol_named_object task_attributes, in boolean pending) ;
		void queues_task_event(in string task_id, in string source, in real delay, in string event_name, in object protocol:consistent_protocol_named_object object) ;
		void queues_task_queue_overflowing(in string task_id, in string queue, in string condition, in string priority) ;
		void queues_task_compute_estimated_waiting_time(in string task_id) ;
		void queues_task_set_pending(in string task_id, in boolean pending) ;
		void queues_task_terminated(in string task_id) ;
		void queues_task_removed(in string task_id) ;
		void queues_task_recover(in string session_id, in string object_id, in string user_task_id, in string queue_type, in string queue_name, in string task_name, in date waiting_date, in real priority, in uint_32 absolute_priority, in object protocol:consistent_protocol_named_object task_attributes, in boolean needs_estimated_waiting_time, in boolean terminated, in uint_32 remote_management_state, in boolean pending) ;
		void queues_user_modify_variable(in string user_id, in date event_date, in string name, in string operation, in real value) ;
		} ;
	interface from
		{
		void queues_connection_ok(in uint_32 server_version) ;
		void queues_queue_add(in string id, in string code, in string name, in string display_name, in string task_name) ;
		void queues_queue_remove(in string id) ;
		void queues_queue_stats(in string id, in uint_32 users_count) ;
		void queues_queue_stats_waiting(in string id, in uint_32 waiting_tasks_count) ;
		void queues_user_locked(in string user_id) ;
		void queues_user_lock_busy(in string user_id) ;
		void queues_session_alert(in uint_32 client_index, in uint_32 session_instance_id, in uint_32 user_task_id, in string task_name, in boolean manually_managed) ;
		void queues_session_error(in uint_32 client_index, in string error) ;
		void queues_session_task_details(in uint_32 client_index, in uint_32 session_instance_id, in uint_32 user_task_id, in string session_id, in string object_id, in string task_id, in string queue_name, in date waiting_date, in real priority, in uint_32 absolute_priority, in object protocol:consistent_protocol_named_object task_attributes, in uint_32 estimated_waiting_time, in string managed_by_queue_name, in string managed_by_queue_display_name) ;
		void queues_session_task_removed(in uint_32 client_index, in uint_32 session_instance_id, in uint_32 user_task_id) ;
		void queues_session_task_terminated(in uint_32 client_index, in uint_32 session_instance_id, in uint_32 user_task_id) ;
		void queues_session_task_event_received(in uint_32 client_index, in uint_32 session_instance_id, in uint_32 user_task_id, in string source, in real delay, in string event_name, in object protocol:consistent_protocol_named_object object) ;
		void queues_session_task_transfer_details(in uint_32 client_index, in uint_32 session_instance_id, in uint_32 user_task_id, in string task_name, in string session_id, in string object_id, in string task_id, in string queue_name, in date waiting_date, in real priority, in uint_32 absolute_priority, in object protocol:consistent_protocol_named_object task_attributes) ;
		void queues_session_task_transferred(in uint_32 client_index, in uint_32 session_instance_id, in uint_32 user_task_id, in string old_manager_task_id, in string old_manager_session_id, in string old_manager_user_id) ;
		void queues_task_display_name(in string session_id, in string task_id, in string display_name) ;
		void queues_task_queue_not_found(in string session_id, in string task_id) ;
		void queues_task_skill_not_found(in string session_id, in string task_id, in string skill_name) ;
		void queues_task_estimated_waiting_time(in string session_id, in string task_id, in uint_32 estimated_waiting_time, in boolean now_idle, in string computed_session_id, in uint_32 computed_session_instance_id, in uint_32 waiting_tasks_count) ;
		void queues_task_event_received(in string session_id, in string task_id, in string source, in real delay, in string event_name, in object protocol:consistent_protocol_named_object object) ;
		void queues_task_overflowing(in string session_id, in string task_id, in string queue_name, in real priority) ;
		void queues_task_alert_pending(in string session_id, in string task_id) ;
		void queues_task_alerting(in string session_id, in string task_id, in string manager_session_id, in string manager_user_id, in string manager_name) ;
		void queues_task_locked(in string session_id, in string task_id, in string manager_session_id, in string manager_user_id, in string manager_name) ;
		void queues_task_managing(in string session_id, in string task_id, in string manager_session_id, in string manager_user_id, in string manager_name) ;
		void queues_task_management_effective(in string session_id, in string task_id, in string manager_session_id, in string manager_user_id, in string manager_name) ;
		void queues_task_post_managing(in string session_id, in string task_id, in string manager_session_id, in string manager_user_id, in string manager_name) ;
		void queues_task_managed(in string session_id, in string task_id, in string manager_session_id, in string manager_user_id, in string reason, in object protocol:consistent_protocol_named_object object, in string manager_name) ;
		void queues_task_management_failed(in string session_id, in string task_id, in string manager_session_id, in string manager_user_id, in string reason, in string manager_name) ;
		void queues_task_failed(in string session_id, in string task_id, in string manager_session_id, in string manager_user_id, in string reason, in string manager_name) ;
		void queues_task_not_manageable(in string session_id, in string task_id, in boolean manually_manageable, in boolean latent_users) ;
		void queues_task_transfer_to(in string session_id, in string task_id, in string remote_session_id, in uint_32 remote_user_task_id) ;
		void queues_stats_session_add(in string session_id, in string user_id, in string display_name, in string state_name, in object ccenter_queues:ccenter_queues_user_state state) ;
		void queues_stats_session_update_state(in string session_id, in string state_name, in object ccenter_queues:ccenter_queues_user_state state) ;
		void queues_stats_session_remove(in string session_id) ;
		void queues_virtual_session_create(in string user_id, in string phone_number) ;
		void queues_virtual_session_destroy(in string user_id) ;
		} ;
	} ;

module call_control_logger
	{
	interface to
		{
		void call_control_logger_process_start() ;
		void call_control_logger_process_stop() ;
		void call_control_logger_alive() ;
		void call_control_logger_create_incoming_call(in string call_id, in string user, in string remote_name, in string remote_address, in string remote_contact, in string local_name, in string local_address, in string aai, in string project_name, in string location_path, in string instance_name, in string entry_point_name, in uint_32 rtp_port, in boolean hidden_number, in string host) ;
		void call_control_logger_create_outgoing_call(in string call_id, in string remote_name, in string remote_address, in string remote_contact, in string local_name, in string local_address, in string aai, in real max_ringing_delay, in string project_name, in string location_path, in string instance_name, in uint_32 rtp_port) ;
		void call_control_logger_add_bad_incoming_call(in string call_id, in string reason, in string user, in string remote_name, in string remote_address, in string remote_contact, in string local_name, in string local_address, in string aai, in string project_name, in string location_path, in string instance_name, in boolean hidden_number, in string host) ;
		void call_control_logger_add_bad_outgoing_call(in string call_id, in string reason, in string remote_name, in string remote_address, in string remote_contact, in string local_name, in string local_address, in string aai, in real max_ringing_delay, in string project_name, in string location_path, in string instance_name) ;
		void call_control_logger_terminate_call(in string call_id, in uint_32 total_bytes_received, in uint_32 total_bytes_sent, in boolean pure_rtp) ;
		void call_control_logger_delete_call(in string call_id) ;
		void call_control_logger_set_call_rtp(in string call_id, in string address, in uint_32 port) ;
		void call_control_logger_set_call_remote_rtp(in string call_id, in string address, in uint_32 port) ;
		void call_control_logger_samples_flow(in string call_id, in uint_32 bytes_received, in uint_32 bytes_sent) ;
		void call_control_logger_input(in string call_id, in uint_32 key) ;
		void call_control_logger_create_dialog(in string dialog_id, in string project_name, in string location_path, in string instance_name) ;
		void call_control_logger_delete_dialog(in string dialog_id) ;
		void call_control_logger_create_conference(in string conference_id, in string project_name, in string location_path, in string instance_name) ;
		void call_control_logger_delete_conference(in string conference_id) ;
		void call_control_logger_join(in string interface_id, in string new_from_id) ;
		void call_control_logger_unjoin(in string interface_id, in string old_from_id) ;
		void call_control_logger_accept_call(in string call_id) ;
		void call_control_logger_reject_call(in string call_id) ;
		void call_control_logger_call_connected(in string call_id) ;
		void call_control_logger_call_disconnected(in string call_id, in string reason) ;
		void call_control_logger_send_transport_message(in string call_id, in string transport_message, in string data, in string to_address) ;
		void call_control_logger_receive_transport_message(in string call_id, in string transport_message, in string data, in string from_address) ;
		} ;
	} ;

module ccxml_logger
	{
	interface to
		{
		void ccxml_logger_process_start() ;
		void ccxml_logger_process_stop() ;
		void ccxml_logger_alive() ;
		void ccxml_logger_session_create(in string session_id, in uint_32 session_type, in boolean recover, in string session_project_name, in string session_project_path) ;
		void ccxml_logger_session_terminate(in string session_id) ;
		void ccxml_logger_session_delete(in string session_id) ;
		void ccxml_logger_session_event(in string session_id, in string source_id, in string target_id, in string state, in string name, in string string_data, in any_object object_data) ;
		void ccxml_logger_session_log(in string session_id, in string source_id, in string type, in string string_data, in any_object object_data) ;
		void ccxml_logger_session_enter_item(in string session_id, in string name, in uint_32 rank, in boolean compute_duration, in string item_name, in string result, in string result_name) ;
		void ccxml_logger_session_add_statistic(in string session_id, in string name, in string value) ;
		void ccxml_logger_session_service_status(in string session_id, in string value) ;
		void ccxml_logger_session_set_entry_point(in string session_id, in string entry_point, in string entry_point_display_name) ;
		void ccxml_logger_session_semantic_error(in string session_id, in string source_id, in string tag_name, in string attribute_name, in string attribute_value, in string reason) ;
		void ccxml_logger_connection_create(in string session_id, in uint_32 connection_id, in string call_id, in string remote_name, in string remote_address, in string remote_contact, in string local_name, in string local_address, in string aai, in uint_32 session_instance_id, in boolean hidden_number, in boolean incoming_call, in string stat_name) ;
		void ccxml_logger_connection_connected(in string session_id, in uint_32 connection_id) ;
		void ccxml_logger_connection_record(in string session_id, in uint_32 connection_id, in string source, in string mode, in string type, in string compression, in string uri, in boolean append) ;
		void ccxml_logger_connection_stop_record(in string session_id, in uint_32 connection_id, in string source) ;
		void ccxml_logger_connection_disconnected(in string session_id, in uint_32 connection_id, in string reason) ;
		void ccxml_logger_connection_terminate(in string session_id, in uint_32 connection_id) ;
		void ccxml_logger_login_failed(in string login, in string reason) ;
		void ccxml_logger_login_ok(in string session_id, in string login, in string name, in uint_32 id, in string mode, in uint_32 instances_count, in string profile_name, in uint_32 profile_id, in string group_name, in string group_display_name, in string group_path, in string user_id, in uint_32 version) ;
		void ccxml_logger_user_still_logged(in string session_id, in string login, in string name, in uint_32 id, in string mode, in uint_32 instances_count, in string profile_name, in uint_32 profile_id, in string group_name, in string group_display_name, in string group_path, in string user_id, in uint_32 version) ;
		void ccxml_logger_logout(in string session_id, in uint_32 id) ;
		void ccxml_logger_set_user_mode(in string session_id, in string mode) ;
		void ccxml_logger_set_instances_count(in string session_id, in uint_32 instances_count) ;
		void ccxml_logger_user_state(in string session_id, in uint_32 state_id, in string name, in string display_name, in string idle_display_name, in string idle_display_color, in uint_32 idle_display_order, in string group, in string display_color, in uint_32 rank) ;
		void ccxml_logger_user_still_in_state(in string session_id, in uint_32 state_id, in string name, in string display_name, in string idle_display_name, in string idle_display_color, in uint_32 idle_display_order, in string group, in string display_color) ;
		void ccxml_logger_user_task_create(in string session_id, in uint_32 task_logger_id, in uint_32 task_id, in string name, in string display_name, in string display_color, in uint_32 display_order, in uint_32 session_instance_id) ;
		void ccxml_logger_user_task_state(in string session_id, in uint_32 task_logger_id, in uint_32 state_id, in string name, in string display_name, in string display_color, in uint_32 display_order, in uint_32 rank) ;
		void ccxml_logger_user_task_lock(in string session_id, in uint_32 task_logger_id) ;
		void ccxml_logger_user_task_locked(in string session_id, in uint_32 task_logger_id, in string caller_session_id, in string caller_object_id, in string caller_task_id, in string queue_name, in date waiting_date, in real priority, in uint_32 absolute_priority, in object protocol:consistent_protocol_named_object task_attributes) ;
		void ccxml_logger_user_task_manage(in string session_id, in uint_32 task_logger_id) ;
		void ccxml_logger_user_task_management_effective(in string session_id, in uint_32 task_logger_id) ;
		void ccxml_logger_user_task_transfer_details(in string session_id, in uint_32 task_logger_id, in string task_name, in string caller_session_id, in string caller_object_id, in string caller_task_id, in string queue_name, in date waiting_date, in real priority, in uint_32 absolute_priority, in object protocol:consistent_protocol_named_object task_attributes) ;
		void ccxml_logger_user_task_post_managing(in string session_id, in uint_32 task_logger_id) ;
		void ccxml_logger_user_task_managed(in string session_id, in uint_32 task_logger_id, in string reason, in object protocol:consistent_protocol_named_object object) ;
		void ccxml_logger_user_task_failed(in string session_id, in uint_32 task_logger_id, in string reason) ;
		void ccxml_logger_user_task_redirected(in string session_id, in uint_32 task_logger_id) ;
		void ccxml_logger_user_task_transferred(in string session_id, in uint_32 task_logger_id, in string manager_task_id, in string manager_session_id, in string manager_user_id) ;
		void ccxml_logger_user_task_temporization_ended(in string session_id, in uint_32 task_logger_id) ;
		void ccxml_logger_user_phone_number(in string session_id, in string uri, in string contact_uri) ;
		void ccxml_logger_user_phone_state(in string session_id, in uint_32 instance_id, in string state) ;
		void ccxml_logger_user_register(in uint_32 user_id, in string call_id, in string phone_id, in string contact, in uint_32 expires, in date expires_date) ;
		void ccxml_logger_dialog_create(in string session_id, in string dialog_id, in string type, in string path_name) ;
		void ccxml_logger_dialog_terminate(in string session_id, in string dialog_id, in string reason) ;
		void ccxml_logger_dialog_enter_item(in string session_id, in string dialog_id, in string form_id, in string item_id, in uint_32 prompt_counter, in uint_32 rank, in boolean compute_duration) ;
		void ccxml_logger_dialog_input(in string session_id, in string dialog_id, in string form_id, in string item_id, in string input) ;
		void ccxml_logger_dialog_event(in string session_id, in string dialog_id, in string form_id, in string item_id, in uint_32 event) ;
		void ccxml_logger_task_start(in string session_id, in string task_id, in string connection_id, in string queue_type, in string queue_name, in string task_name, in date waiting_date, in real priority, in uint_32 absolute_priority, in object protocol:consistent_protocol_named_object task_attributes, in string skills) ;
		void ccxml_logger_task_display_name(in string session_id, in string task_id, in string display_name) ;
		void ccxml_logger_task_estimated_waiting_time(in string session_id, in string task_id, in uint_32 estimated_waiting_time) ;
		void ccxml_logger_task_not_manageable(in string session_id, in string task_id) ;
		void ccxml_logger_task_overflowing(in string session_id, in string task_id, in string queue, in real priority) ;
		void ccxml_logger_task_alerting(in string session_id, in string task_id, in string manager_session_id, in string manager_user_id) ;
		void ccxml_logger_task_locked(in string session_id, in string task_id, in string manager_session_id, in string manager_user_id) ;
		void ccxml_logger_task_managing(in string session_id, in string task_id, in string manager_session_id, in string manager_user_id) ;
		void ccxml_logger_task_management_effective(in string session_id, in string task_id, in string manager_session_id, in string manager_user_id) ;
		void ccxml_logger_task_post_managing(in string session_id, in string task_id, in string manager_session_id, in string manager_user_id) ;
		void ccxml_logger_task_management_failed(in string session_id, in string task_id, in string manager_session_id, in string manager_user_id, in string reason) ;
		void ccxml_logger_task_result(in string session_id, in string task_id, in string reason, in object protocol:consistent_protocol_named_object values) ;
		void ccxml_logger_task_failed(in string session_id, in string task_id, in string reason) ;
		void ccxml_logger_task_add_scripting_value(in string session_id, in string task_id, in string name, in string value) ;
		} ;
	} ;

module queues_logger
	{
	interface to
		{
		void queues_logger_process_start() ;
		void queues_logger_process_stop() ;
		void queues_logger_alive() ;
		void queues_logger_queue_add(in string id, in string display_name, in string name, in string task_name, in string code, in string group_name, in string queue_type) ;
		void queues_logger_queue_still_running(in string id, in string display_name, in string name, in string task_name, in string code, in string group_name, in string queue_type) ;
		void queues_logger_queue_remove(in string id) ;
		void queues_logger_task_add(in string id, in string display_name, in string name) ;
		void queues_logger_task_remove(in string id) ;
		void queues_logger_session_add(in string session_id, in string user_id, in date event_date, in string state_name, in object ccenter_queues:ccenter_queues_user_state state, in uint_32 wanted_instances_count) ;
		void queues_logger_session_remove(in string session_id) ;
		void queues_logger_session_set_instances_count(in string session_id, in uint_32 wanted_instances_count, in uint_32 instances_count) ;
		void queues_logger_session_set_working_instances_count(in string session_id, in uint_32 working_instances_count) ;
		void queues_logger_session_set_waiting_date(in string session_id, in uint_32 session_instance_id, in date waiting_date) ;
		void queues_logger_session_update_queues(in string session_id, in object ccenter_queues:ccenter_queues_user_state state, in date state_date, in string state_name) ;
		void queues_logger_session_add_extra_service(in string session_id, in string service, in real priority, in real skill, in uint_32 min_absolute_priority) ;
		void queues_logger_session_remove_extra_service(in string session_id, in string service) ;
		void queues_logger_file_task_add(in string session_id, in string object_id, in string task_id, in string queue_type, in string queue_name, in string task_name, in date waiting_date, in real priority, in uint_32 absolute_priority, in object protocol:consistent_protocol_named_object task_attributes, in string group, in string skills, in boolean pending) ;
		void queues_logger_file_task_alert_pending(in string task_id) ;
		void queues_logger_file_task_modify_pending(in string task_id, in boolean new_pending) ;
		void queues_logger_file_task_alerting(in string task_id, in string managed_by_queue_display_name, in string managed_by_queue_name, in string managed_by_queue_task_name, in string manager_session_id, in string manager_user_id, in string manager_name) ;
		void queues_logger_file_task_locked(in string task_id, in string managed_by_queue_display_name, in string managed_by_queue_name, in string managed_by_queue_task_name, in string manager_session_id, in string manager_user_id, in string manager_name) ;
		void queues_logger_file_task_managing(in string task_id) ;
		void queues_logger_file_task_management_effective(in string task_id) ;
		void queues_logger_file_task_joined(in string task_id) ;
		void queues_logger_file_task_unjoined(in string task_id) ;
		void queues_logger_file_task_post_managing(in string task_id) ;
		void queues_logger_file_task_managed(in string task_id, in string reason, in object protocol:consistent_protocol_named_object results) ;
		void queues_logger_file_task_failed(in string task_id, in string reason) ;
		void queues_logger_file_task_management_failed(in string task_id) ;
		} ;
	} ;

module proxy_logger
	{
	interface to
		{
		void proxy_logger_process_start() ;
		void proxy_logger_process_stop() ;
		void proxy_logger_alive() ;
		void proxy_logger_create_incoming_call(in string call_id, in string user, in string remote_name, in string remote_address, in string remote_contact, in string local_name, in string local_address, in string aai, in string project_name, in string location_path, in string instance_name, in string entry_point_name, in uint_32 rtp_port, in boolean hidden_number, in string host) ;
		void proxy_logger_create_outgoing_call(in string call_id, in string remote_name, in string remote_address, in string remote_contact, in string local_name, in string local_address, in string aai, in real max_ringing_delay, in string project_name, in string location_path, in string instance_name, in uint_32 rtp_port) ;
		void proxy_logger_add_bad_incoming_call(in string call_id, in string reason, in string user, in string remote_name, in string remote_address, in string remote_contact, in string local_name, in string local_address, in string aai, in string project_name, in string location_path, in string instance_name, in boolean hidden_number, in string host) ;
		void proxy_logger_add_bad_outgoing_call(in string call_id, in string reason, in string remote_name, in string remote_address, in string remote_contact, in string local_name, in string local_address, in string aai, in real max_ringing_delay, in string project_name, in string location_path, in string instance_name) ;
		void proxy_logger_terminate_call(in string call_id, in uint_32 total_bytes_received, in uint_32 total_bytes_sent) ;
		void proxy_logger_delete_call(in string call_id) ;
		void proxy_logger_accept_call(in string call_id) ;
		void proxy_logger_reject_call(in string call_id) ;
		void proxy_logger_call_connected(in string call_id) ;
		void proxy_logger_call_disconnected(in string call_id, in string reason) ;
		void proxy_logger_send_transport_message(in string call_id, in string transport_message, in string data, in string to_address) ;
		void proxy_logger_receive_transport_message(in string call_id, in string transport_message, in string data, in string from_address) ;
		void proxy_logger_set_call_remote_rtp(in string call_id, in string address, in uint_32 port) ;
		void proxy_logger_create_dialog(in string dialog_id, in string project_name, in string location_path, in string instance_name) ;
		void proxy_logger_delete_dialog(in string dialog_id) ;
		void proxy_logger_create_conference(in string conference_id, in string project_name, in string location_path, in string instance_name) ;
		void proxy_logger_delete_conference(in string conference_id) ;
		} ;
	} ;

module dispatch_logger
	{
	interface to
		{
		void dispatch_logger_process_start() ;
		void dispatch_logger_process_stop() ;
		void dispatch_logger_alive() ;
		} ;
	} ;

module db_logger_logger
	{
	interface to
		{
		void db_logger_logger_process_start() ;
		void db_logger_logger_process_stop() ;
		void db_logger_logger_alive() ;
		} ;
	} ;

module scheduler_logger
	{
	interface to
		{
		void scheduler_logger_process_start() ;
		void scheduler_logger_process_stop() ;
		void scheduler_logger_alive() ;
		void scheduler_logger_add_outbound(in string explorer_id, in string path, in string name) ;
		void scheduler_logger_remove_outbound(in string explorer_id) ;
		void scheduler_logger_outbound_description(in string explorer_id, in string state, in boolean active, in string default_ccxml_instance_name, in string default_entry_point_name, in string default_mode, in uint_32 prefetch, in string task_name, in string queue_name, in string display_name) ;
		void scheduler_logger_outbound_contacts_count(in string explorer_id, in uint_32 not_managed, in uint_32 call_again, in uint_32 managed_ok, in uint_32 managed_nok, in uint_32 burnt) ;
		void scheduler_logger_add_calendar(in string explorer_id, in string path, in string name) ;
		void scheduler_logger_remove_calendar(in string explorer_id) ;
		void scheduler_logger_calendar_description(in string explorer_id, in string display_name) ;
		} ;
	} ;

module alert_logger
	{
	interface to
		{
		void alert_logger_process_start() ;
		void alert_logger_process_stop() ;
		void alert_logger_alive() ;
		} ;
	} ;

module update_server_logger
	{
	interface to
		{
		void update_server_logger_process_start() ;
		void update_server_logger_process_stop() ;
		void update_server_logger_alive() ;
		} ;
	} ;

module tts_logger
	{
	interface to
		{
		void tts_logger_process_start() ;
		void tts_logger_process_stop() ;
		void tts_logger_alive() ;
		} ;
	} ;

web_service proxy_web_service
	{
	interface to
		{
		void create_session(in string password, in string module, in string entry_point, in string arguments) ;
		void add_calendar_event(in string password, in string module, in string calendar_name, in string civility, in string display_name, in string contact, in string entry_point, in string service, in string mode, in uint_32 absolute_priority, in date event_date, in uint_32 duration, in string values) ;
		} ;
	interface from
		{
		void create_session_result(in uint_32 code, in string reason) ;
		void add_calendar_event_result(in uint_32 code, in string reason, in string event_id) ;
		} ;
	} ;
