#!/usr/bin/env python3
from cccp.project import ProjectConfig, ConfigDB
from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument("project", help="Consistent project name")
parser.add_argument("number")
parser.add_argument("entry_type")
parser.add_argument("-i","--ip", help="Host IP", default="127.0.0.1", nargs="?")
args = parser.parse_args()

class ProjectEntries:
    # Se connecte sur la base de données du serveur CST
    def __init__(self, ip, project):
        self.project = project
        self.cdb = ConfigDB(ip)    # Connexion à la racine de la base de données CST.

        # Les points d'entrées ccxml sont décrits dans le fichier Ccxml.xml de chaque projet.
        self.pdb = ProjectConfig(project,ip)   # Connexion au répertoire du projet dans la base de données CST.

    def get_entry_name_from_number(self,number):
        for e in self.cdb.get("/db/projects/Main/Voip.xml").entrys:
            if e.project_name == self.project and e.value == number:
                return e.entry_point_name

    def _set_entry_type( _, ccxml_config, entry_name, entry_type):
        for e in ccxml_config.entrys:
            if e.name == entry_name:
                for v in e.values:
                    if v.name == 'project_type_cfg':
                        v.value = entry_type
                        return

    def set_entry_type(self,entry_name, entry_type):
        ccxml_config = self.pdb.get("Ccxml.xml")
        self._set_entry_type(ccxml_config, entry_name, entry_type)
        self.pdb.put("Ccxml.xml", ccxml_config)

entries = ProjectEntries(args.ip, args.project)

entry_name = entries.get_entry_name_from_number(args.number)

entries.set_entry_type(entry_name, args.entry_type)
