#!/usr/bin/env php

<?php
include_once '/opt/data/apache2_htdocs/plexid.live/adm/conf/local/identity.conf.php';
include_once '/opt/data/apache2_htdocs/plexid.live/adm/conf/local/mysql.conf.php';

$db = new mysqli(
	$_HOST,
	$_DBUSER,
	$_DBPASSWORD,
	'w' . constant('WEBNODE') . 'interactivnetadmin'
);

$result = $db->query('select `id`, `configuration` from `adm_vocal_agents_profiles`');

$checked = 0;
$updated = 0;

while ( $row = $result->fetch_assoc() ) {
	$configuration = unserialize($row['configuration']);

	if ( ! array_key_exists('outgoing_agent_callerid_type', $configuration) || $configuration['outgoing_agent_callerid_type'] == 'default' ) {
		$configuration['outgoing_agent_callerid_type'] = 'position';

		$db->query("update `adm_vocal_agents_profiles` set `configuration` = '" . serialize($configuration) . "' where `id` = " . $row['id']);

		$updated ++;
	}

	$checked ++;

	printf("\rChecked %7d - Updated %7d", $checked, $updated);
}

print "\n";
?>