#!/usr/bin/env bash

source iv-static-ports >/dev/null 2>&1 \
	|| (echo "Couldn't find \`iv-static-ports'. Exiting." && exit 2)

project_exists() {
	local project_name="$1"
	"get_projects" | grep -E "^$project_name\$" >/dev/null 2>&1
}

ccc_mkdir() {
	local path="$1"
	debug "Creating path \`$path'."
	ccc_update 20000 -mknode "$path"
}

upload_template_for_process() {
	local process_name="$1"
	local project_name="$2"
	local base_port="$3"
	local sqlconnstring="$4"
	local path="$(get_path_for_process "$process_name" "$project_name")"
	local filename="$(get_local_filename "$path")"

	debug "Uploading process description template for \`$path'."

	case "$process_name" in
		Cdr)
			cat <<HEREDOC > "$filename"
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<com.consistent.head.consistent_stand_alone_process id="_1" class_name="cdr" 
	process_name="ccenter_cdr" max_stop_duration="0" 
	max_respawn_count="1" max_respawn_duration="0" retry_interval="5" 
	big_retry_interval="0" active="1" scheduling_policy="0" 
	scheduling_priority="0" lock_memory="0" kill_number="0">
	<arguments>
		<consistent_process_argument id="_2" value="$project_name"/>
	</arguments>
</com.consistent.head.consistent_stand_alone_process>
HEREDOC
		;;

		Proxy)
			local port=$(get_port_for_process "ccenter_proxy" "$project_name" \
				"$base_port")
			cat <<HEREDOC > "$filename"
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<com.consistent.ccenter.proxy.ccenter_proxy_process id="_1" class_name="proxy"
		process_name="ccenter_proxy" max_stop_duration="2000"
		max_respawn_count="5" max_respawn_duration="10000" retry_interval="2000"
		big_retry_interval="5000" active="1" scheduling_policy="0"
		scheduling_priority="0" lock_memory="0" max_http_cache_item_size="0"
		max_http_cache_item_expires="0" http_cache_reset_date=""
		listen_port="$port" strict_address="0" sip_port="0"
		user_location="consistent_1/Head_Main/Head_$project_name"
		user_instance_name="Ccxml" www_root="cdep://head/db/www"
		explorer_no_responses_timeout="20" explorer_disconnected_timeout="20"
		connection_check_interval="0" ftp_port="0" ftp_max_users="0"
		ftp_timeout="0" ftp_first_data_port="0" ftp_last_data_port="0">
	<explorer_modules>
		<ccenter_proxy_process_explorer_module id="_10001" path_name="/db"
				process_class="consistent_head" strict="0" remove_path="0"/>
		<ccenter_proxy_process_explorer_module id="_10002" path_name="/dispatch"
				process_class="ccenter_dispatch" strict="0" remove_path="0"/>
		<ccenter_proxy_process_explorer_module id="_10003" path_name="/store"
				process_class="consistent_store" strict="0" remove_path="0"/>
		<ccenter_proxy_process_explorer_module id="_10004"
				path_name="/scheduler" process_class="ccenter_scheduler"
				strict="0" remove_path="0"/>
	</explorer_modules>
</com.consistent.ccenter.proxy.ccenter_proxy_process>
HEREDOC
			;;

		Dispatch)
			local port=$(get_port_for_process "ccenter_dispatch" \
				"$project_name" "$base_port")
			cat <<HEREDOC > "$filename"
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<com.consistent.ccenter.dispatch.ccenter_dispatch_process id="_1"
		class_name="dispatch" process_name="ccenter_dispatch"
		max_stop_duration="2000" max_respawn_count="5"
		max_respawn_duration="10000" retry_interval="2000"
		big_retry_interval="5000" active="1" scheduling_policy="0"
		scheduling_priority="0" lock_memory="0" max_http_cache_item_size="0"
		max_http_cache_item_expires="0" http_cache_reset_date=""
		listen_port="$port" hours_history="0" hours_restart="0"
		hours_details="0" hours_debug="0" hours_ended_sessions="0"
		hours_ended_contacts="0" hours_ended_interfaces="0"
		session_hash_size="0" task_hash_size="0" interface_hash_size="0">
	<computed_projects>
		<ccenter_dispatch_process_project id="_2" project_name="$project_name"
				location="consistent_1/Head_Main/Head_$project_name"
				instance_name="Logger" decode_proxy="0" decode_voip="0"
				decode_ccxml="0" decode_queues="0" decode_scheduler="0"
				decode_debug="1"/>
	</computed_projects>
</com.consistent.ccenter.dispatch.ccenter_dispatch_process>
HEREDOC
			;;

		Logger)
			local port=$(get_port_for_process "consistent_logger" \
				"$project_name" "$base_port")
			cat <<HEREDOC > "$filename"
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<com.consistent.head.consistent_logger_process id="_1" class_name="logger"
		process_name="consistent_logger" max_stop_duration="2000"
		max_respawn_count="5" max_respawn_duration="10000" retry_interval="2000"
		big_retry_interval="5000" active="1" scheduling_policy="0"
		scheduling_priority="0" lock_memory="0" max_http_cache_item_size="0"
		max_http_cache_item_expires="0" http_cache_reset_date=""
		listen_port="$port" recover_bytes_per_second="0"/>
HEREDOC
			;;

		Ccxml)
			local port=$(get_port_for_process "ccenter_ccxml" "$project_name" \
				"$base_port")
			cat <<HEREDOC > "$filename"
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<com.consistent.ccenter.ccxml.ccenter_ccxml_process id="_1" class_name="ccxml"
		process_name="ccenter_ccxml" max_stop_duration="2000"
		max_respawn_count="5" max_respawn_duration="10000" retry_interval="2000"
		big_retry_interval="5000" active="1" scheduling_policy="0"
		scheduling_priority="0" lock_memory="0" max_http_cache_item_size="0"
		max_http_cache_item_expires="0" http_cache_reset_date=""
		listen_port="$port" configuration="/db/projects/$project_name/Ccxml.xml"
		scheduling_ccxml_priority="0">
	<queues>
		<ccenter_ccxml_process_queue id="_2" name="Default"
				project_name="$project_name"
				location="consistent_1/Head_Main/Head_$project_name"
				instance_name="Queues"/>
	</queues>
	<explorer_modules>
		<ccenter_ccxml_process_explorer_module id="_4"
				path_name="/$project_name" process_class="consistent_store"
				project_name="$project_name"
				location_path="consistent_1/Head_Main/Head_$project_name"
				instance_name="Store" strict="0" remove_path="0"/>
	</explorer_modules>
</com.consistent.ccenter.ccxml.ccenter_ccxml_process>
HEREDOC
			;;

		Queues)
			local port=$(get_port_for_process "ccenter_queues" "$project_name" \
				"$base_port")
			cat <<HEREDOC > "$filename"
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<com.consistent.ccenter.queues.ccenter_queues_process id="_1"
		class_name="queues" process_name="ccenter_queues"
		max_stop_duration="2000" max_respawn_count="5"
		max_respawn_duration="10000" retry_interval="2000"
		big_retry_interval="5000" active="1" scheduling_policy="0"
		scheduling_priority="0" lock_memory="0" max_http_cache_item_size="0"
		max_http_cache_item_expires="0" http_cache_reset_date=""
		listen_port="$port"
		configuration="/db/projects/$project_name/Queues.xml"/>
HEREDOC
			;;

		Mysql)
			local port=$(get_port_for_process "consistent_mysql_ws" \
				"$project_name" "$base_port")
			local mysql_username="$(connstring_username "$sqlconnstring")"
			local mysql_password="$(connstring_password "$sqlconnstring")"
			local mysql_hostname="$(connstring_hostname "$sqlconnstring")"
			local mysql_port="$(connstring_port "$sqlconnstring")"
			local mysql_dbname="$(connstring_dbname "$sqlconnstring")"
			cat <<HEREDOC > "$filename"
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<com.consistent.mysql_ws.consistent_mysql_ws_process id="_1"
		class_name="mysql_ws" process_name="consistent_mysql_ws"
		max_stop_duration="2000" max_respawn_count="5"
		max_respawn_duration="10000" retry_interval="2000"
		big_retry_interval="5000" active="1" scheduling_policy="0"
		scheduling_priority="0" lock_memory="0" max_http_cache_item_size="0"
		max_http_cache_item_expires="0" http_cache_reset_date=""
		listen_port="$port" mysql_host="$mysql_hostname"
		mysql_port="$mysql_port" mysql_user="$mysql_username"
		mysql_password="$mysql_password" mysql_data_base_name="$mysql_dbname"/>
HEREDOC
			;;

		Store)
			local port=$(get_port_for_process "consistent_store" \
				"$project_name" "$base_port")
			cat <<HEREDOC > "$filename"
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<com.consistent.store.consistent_store_process id="_1" class_name="store"
		process_name="consistent_store" max_stop_duration="2000"
		max_respawn_count="5" max_respawn_duration="10000" retry_interval="2000"
		big_retry_interval="5000" active="1" scheduling_policy="0"
		scheduling_priority="0" lock_memory="0" max_http_cache_item_size="0"
		max_http_cache_item_expires="0" http_cache_reset_date=""
		listen_port="$port" discard_timeout="20"/>
HEREDOC
			;;

		Head_*)
			local port=$(get_port_for_process "consistent_head" \
				"$project_name" "$base_port")
			cat <<HEREDOC > "$filename"
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<com.consistent.head.consistent_head_process id="_1" class_name="head"
		process_name="consistent_head" max_stop_duration="2000"
		max_respawn_count="5" max_respawn_duration="10000" retry_interval="2000"
		big_retry_interval="5000" active="1" scheduling_policy="0"
		scheduling_priority="0" lock_memory="0" max_http_cache_item_size="0"
		max_http_cache_item_expires="0" http_cache_reset_date=""
		listen_port="$port" first_dynamic_port="0" last_dynamic_port="0">
	<loggers>
		<consistent_head_process_logger id="_2"
				logger_location="consistent_1/Head_Main/Head_$project_name"
				logger_instance_name="Logger"/>
	</loggers>
</com.consistent.head.consistent_head_process>
HEREDOC
			;;

	esac

	put_file "$path"
	rm -rf "$filename"
}

create_processes() {
	local project_name="$1"
	local base_port="$2"
	local sqlconnstring="$3"

	upload_template_for_process "Head_$project_name" "$project_name" \
		"$base_port"

	local processes="Proxy Dispatch Logger Ccxml Queues Mysql Store Cdr"

	for process in $processes; do
		local path="$(get_path_for_process "$process" "$project_name")"
		upload_template_for_process "$process" "$project_name" "$base_port" \
			"$sqlconnstring"
	done
}

create_structure() {
	local project_name="$1"
	local directories="$project_name
		$project_name/processes
		$project_name/processes/consistent_1
		$project_name/processes/consistent_1/Head_Main
		$project_name/processes/consistent_1/Head_Main/Head_$project_name"

	for directory in $directories; do
		ccc_mkdir "/db/projects/$directory"
	done
}

ccc_copy() {
	local src="$1"
	local dst="$2"
	local filename="$(get_local_filename "$src")"

	debug "Copying \`$src' to \`$dst'."

	get_file "$src"
	put_file "$dst"
	rm -rf "$filename"
}

create_base_files() {
	local project_name="$1"
	local files="Agent_Default.xml Scenario.xml Outbound.xml sda_default.xml phone-login.xml"

	for file in $files; do
		ccc_copy "/db/projects/Default/$file" "/db/projects/$project_name/$file"
	done

	local filename=""

	cat <<HEREDOC > Queues.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<com.consistent.ccenter.queues.ccenter_queues id="_1"
		max_estimated_waiting_time="0" max_virtual_agent_idle_time="0">
	<tasks>
		<ccenter_queues_task id="_3" name="inbound" display_name="appels entrants"/>
		<ccenter_queues_task id="_5" name="outbound" display_name="appels sortants"/>
	</tasks>
</com.consistent.ccenter.queues.ccenter_queues>
HEREDOC
	filename="/db/projects/$project_name/Queues.xml"
	debug "Uploading initial version of \`$filename'."
	put_file "$filename"
	rm -rf Queues.xml

cat <<HEREDOC > Ccxml.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<com.consistent.ccenter.ccxml.ccenter_ccxml id="_1" max_form_item_steps="0"
		max_form_items_by_minute="0" min_explorer_version="0"
		register_test_interval="0">
	<regular_days>
		<ccenter_ccxml_regular_day id="_503001" from_day="0" from="0" to_day="0"
				to="0" day_name="_5020010"/>
		<ccenter_ccxml_regular_day id="_503002" from_day="1" from="0" to_day="1"
				to="0" day_name="_5020011"/>
		<ccenter_ccxml_regular_day id="_503003" from_day="2" from="0" to_day="2"
				to="0" day_name="_5020012"/>
		<ccenter_ccxml_regular_day id="_503004" from_day="3" from="0" to_day="3"
				to="0" day_name="_5020013"/>
		<ccenter_ccxml_regular_day id="_503005" from_day="4" from="0" to_day="4"
				to="0" day_name="_5020014"/>
		<ccenter_ccxml_regular_day id="_503006" from_day="5" from="0" to_day="5"
				to="0" day_name="_5020015"/>
		<ccenter_ccxml_regular_day id="_503007" from_day="6" from="0" to_day="6"
				to="0" day_name="_5020016"/>
		<ccenter_ccxml_regular_day id="_503008" from_day="0" from="0" to_day="6"
				to="0" day_name="_5020017"/>
	</regular_days>
	<day_names>
		<ccenter_ccxml_day_name id="_5020010" name="day_1"/>
		<ccenter_ccxml_day_name id="_5020011" name="day_2"/>
		<ccenter_ccxml_day_name id="_5020012" name="day_3"/>
		<ccenter_ccxml_day_name id="_5020013" name="day_4"/>
		<ccenter_ccxml_day_name id="_5020014" name="day_5"/>
		<ccenter_ccxml_day_name id="_5020015" name="day_6"/>
		<ccenter_ccxml_day_name id="_5020016" name="day_7"/>
		<ccenter_ccxml_day_name id="_5020017" name="all_days"/>
	</day_names>
	<states>
		<ccenter_ccxml_user_state id="_1001000000" name="supervision"
				display_name="supervision" idle_display_name="supervision"
				idle_display_color="#EEEEEE" idle_display_order="11"/>
		<ccenter_ccxml_user_state id="_1005000000" name="aide_supervision"
				display_name="aide &#38; supervision" idle_display_name="libre"
				idle_display_color="#EEEEEE" idle_display_order="11"/>
		<ccenter_ccxml_user_state id="_1006000000" name="room_traitement"
				display_name="room_traitement" idle_display_name="libre"
				idle_display_color="#EEEEEE" idle_display_order="11"/>
	</states>
	<modes>
		<ccenter_ccxml_mode id="_4012040000"
				display_name="Interface superviseur" name="supervisor interface"
				group="interface" initial_state="_1001000000"/>
		<ccenter_ccxml_mode id="_4012050000" display_name="Register superviseur"
				name="supervisor register" group="register"
				initial_state="_1001000000"/>
		<ccenter_ccxml_mode id="_4012060000" display_name="Unplug superviseur"
				name="supervisor unplug" group="unplug"
				initial_state="_1001000000"/>
		<ccenter_ccxml_mode id="_4012070000" display_name="room_active"
				name="room_active" group="scheduling"
				initial_state="_1006000000"/>
	</modes>
	<tasks>
		<ccenter_ccxml_user_task id="_2001000000" name="inbound"
				display_name="appel entrant" display_color="#00FF00"
				display_order="1"/>
	</tasks>
	<entrys>
		<ccenter_ccxml_entry id="_3481899" name="agent_outbound" scenario="Outbound.xml" disconnected_timeout="0">
			<values>
				<com.consistent.protocol.consistent_protocol_named_object_value_string id="_3482899" name="accueil" value="sda_default.xml"/>
				<com.consistent.protocol.consistent_protocol_named_object_value_string id="_3483899" name="project_type_cfg" value="outbound"/>
				<com.consistent.protocol.consistent_protocol_named_object_value_string id="_3484899" name="delay_cfg" value="0"/>
			</values>
		</ccenter_ccxml_entry>
	</entrys>
</com.consistent.ccenter.ccxml.ccenter_ccxml>
HEREDOC
	filename="/db/projects/$project_name/Ccxml.xml"
	debug "Uploading initial version of \`$filename'."
	put_file "$filename"
	rm -rf Ccxml.xml
}

has_store_explorer_module() {
	local project="$1"
	local filename="$2"

	grep -q "<ccenter_voip_process_explorer_module.*project_name=\"$project\""\
		"$filename"
}

has_previous_explorer_modules() {
	local filename="$1"

	grep -q '<explorer_modules>' "$filename"
}

get_next_file_id() {
	local filename="$1"
	local id=1

	while grep -q "id=\"_$id\"" "$filename"; do
		id=$(($id + 1))
	done

	echo "_$id"
}

update_voip() {
	local project="$1"
	local path="/db/projects/Main/processes/consistent_1/Head_Main/Voip_1"
	local filename="$(get_local_filename "$path")"

	get_file "$path"

	local id=$(get_next_file_id "$filename")
	local line=$(cat <<HEREDOC
<ccenter_voip_process_explorer_module id="$id" path_name="/$project"
		process_class="consistent_store" project_name="$project"
		location_path="consistent_1/Head_Main/Head_$project"
		instance_name="Store" strict="0" remove_path="0" />
HEREDOC
)

	if has_store_explorer_module "$project" "$filename"; then
		debug "Voip_1 process already has a Store registered for project "\
			"\`$project'. No modification required."

	elif has_previous_explorer_modules "$filename"; then
		debug "Updating Voip_1 to know about \`$project' Store process."

		while read l; do
			if [[ $l =~ '</explorer_modules>' ]]; then
				echo $line
			fi
			echo "$l"
		done < "$filename" > "$filename-tmp"
		mv "$filename-tmp" "$filename"

		put_file "$path"

	else
		debug "Updating Voip_1 to know about \`$project' Store process."

		while read l; do
			if [[ $l =~ '</com.consistent.ccenter.voip.ccenter_voip_process>' ]]
			then
				echo "<explorer_modules>$line</explorer_modules>"
			fi
			echo "$l"
		done < "$filename" > "$filename-tmp"
		mv "$filename-tmp" "$filename"

		put_file "$path"
	fi

	rm -rf "$filename"
}

main() {
	init_globals
	check_binaries

	local current_dir="$(pwd)"
	local tmpdir=$(mktemp -d)
	cd "$tmpdir"

	export server_address="$1"
	local project="$2"
	local sqlconnstring="$3"

	if project_exists "$project"; then
		die "Project \`$project' already exists on this server."
	else
		debug "Creating new project with name: \`$project'"
	fi

#	user_confirm "This will create a new project called $project!"

	local base_port=$(get_next_available_port)

	if [ $(get_projects_using_dynamic_ports | wc -l) -gt 0 ]; then
		echo "Error: found projects using dynamic ports:"
		get_projects_using_dynamic_ports
		echo "Project not created. Exiting."
	else
		create_structure "$project"
		create_base_files "$project"
		create_processes "$project" "$base_port" "$sqlconnstring"
		update_voip "$project"
	fi

	delete_caches
	cd "$current_dir"
	rm -rf "$tmpdir"
}

show_help() {
	cat << EOF
Usage: ${0##*/} [-h] [-s SERVER] PROJECT SQLCONNSTRING

Create a new project on an IV2US vocal node. This project will use static ports,
so the server should have been converted to using static ports prior to using
this script. If the server is using dynamic port allocation, please use the old
\`socket_client' binary. If SERVER is provided, use that address instead of
\`localhost' to talk to the server.

Positional arguments:
    PROJECT       the name of the project that should be created.
    SQLCONNSTRING a MySQL connection string describing the database to which
                  the mysql_ws process should connect to. Example:
                      mysql://user:password@hostname:port/db_name

Options:
    -h        display this help message and exit.
    -s SERVER specify the address of the server to which we should connect. If
              not provided, this will default to \`localhost'.
EOF
}

validate_sqlconnstring() {
	local sqlconnstring="$1"
	local regex='^mysql://[^:]+:[^@]+@[^:]+:[0-9]+/.+$'

	if [[ ! $sqlconnstring =~ $regex ]]; then
		return 1
	else
		return 0
	fi
}

connstring_result() {
	if [[ $1 =~ $2 ]]; then
		echo "${BASH_REMATCH[1]}"
	fi
}

connstring_username() {
	connstring_result "$1" '^mysql://([^:]+):'
}

connstring_password() {
	connstring_result "$1" '^mysql://[^:]+:([^@]+)@'
}

connstring_hostname() {
	connstring_result "$1" '^mysql://[^:]+:[^@]+@([^:]+):'
}

connstring_port() {
	connstring_result "$1" '^mysql://[^:]+:[^@]+@[^:]+:([0-9]+)/'
}

connstring_dbname() {
	connstring_result "$1" '^mysql://[^:]+:[^@]+@[^:]+:[0-9]+/(.+)$'
}

if [[ $0 =~ iv-new-project ]]; then
	server="localhost"

	while getopts "hs:" opt; do
		case "$opt" in
			h)
				show_help
				exit 0
				;;

			s)
				server="$OPTARG"
				;;

			'?')
				show_help >&2
				exit 1
				;;
		esac
	done

	project="${@:$OPTIND:1}"
	sqlconnstring="${@:$OPTIND+1:2}"

	if [[ $project == "" ]]; then
		die "The PROJECT argument is required."
	fi

	if [[ $sqlconnstring == "" ]]; then
		die "The SQLCONNSTRING argument is required."
	elif ! validate_sqlconnstring "$sqlconnstring"; then
		die "The SQLCONNSTRING argument could not be parsed. Valid format:
    mysql://username:password@hostname:port/db_name"
	fi

	main "$server" "$project" "$sqlconnstring"
fi
