#!/usr/bin/env python
# coding: utf-8

# Created: 2019-04-26
# Authors:
#    - JTAG <jtag@interact-iv.com>

from __future__ import print_function

from argparse import ArgumentParser
from cnx_ccc_xml_tk.CccUtils import ccc_get, ccc_put
from cnx_ccc_xml_tk.XmlParser import XmlParser
from os import path
import sys


parser = ArgumentParser(description="Set project common values.")

parser.add_argument(dest="host", help="Target vocal host")
parser.add_argument(dest="project", help="Target project")
parser.add_argument("--country", dest="country_cfg", default=None, help="Country. Ex: FR, PT, UK, ...")
parser.add_argument("--whitelabel", dest="whitelabel_cfg", default=None, help="Whitelabel. Ex: COLT, CONNECTICS, ...")
parser.add_argument("--project", dest="project_cfg", default=None, help="Project. Ex: INT101, INTERACTIVSUPPORTMC, ...")
parser.add_argument("--pai", dest="p_asserted_identity_cfg", default=None, help="P-Asserted-Identity. Ex: <sip:0544332211@cnxtestsuite.com>")
parser.add_argument("--backup_directory", default="/tmp", help="Backup directory used for local copy of current and updated Ccxml configurations. Default: /tmp")
parser.add_argument("-d", "--debug", help="Debug mode. File won't be pushed back to vocal server.", default=False, action='store_true')

args = parser.parse_args()
remote_path = "/db/projects/%s/Ccxml.xml" % args.project
backup_filename = path.join(args.backup_directory, "%s_old_Ccxml.xml" % args.project)
updated_filename = path.join(args.backup_directory, "%s_new_Ccxml.xml" % args.project)
user = "admin"
password = "admin"

ccc_get(args.host, remote_path, backup_filename)

with open(updated_filename, 'w') as updated_file:
    print("Cleaning file...", end="")
    sys.stdout.flush()
    for line in open(backup_filename, 'r').readlines():
        if "com.consistent.ccenter.ccxml.ccenter_ccxml_user-:" not in line:
            updated_file.write(line)

    print("done")
    sys.stdout.flush()

xparser = XmlParser()
xparser.load(updated_filename)
print("Updating local file... ")
sys.stdout.flush()

for _path in ('users_values', 'entries_values'):
    print("Handling %s:" % _path)
    for name in ('country_cfg', 'whitelabel_cfg', 'project_cfg', 'p_asserted_identity_cfg'):
        value = getattr(args, name)
        if not value:
            print(" - %-24s: %s" % (name, xparser.get_named_object_value(_path, name)))
        else:
            print(" - %-24s: %s -> %s" % (name, xparser.set_named_object(_path, name, value), value))

xparser.save(updated_filename)
print("Done")
sys.stdout.flush()

if not args.debug:
    ccc_put(args.host, remote_path, updated_filename)
else:
    print("Debug mode. File has not been pushed back to server.")

print("Old ccxml file: %s" % backup_filename)
print("New ccxml file: %s" % updated_filename)
