#!/usr/bin/env python
# coding: utf-8

import argparse
import MySQLdb
import sys

from twisted.internet import defer, reactor, task
from ivcommons.apiclients import RecordsAPIClient

DEFAULT_SQL_USER = 'interactiv'


def parse_arguments():
    parser = argparse.ArgumentParser(
        description="Import records from webadmin to records api.")

    parser.add_argument(
        '-p', '--project', required=True,
        help="project name to which the import should be limited. ")
    parser.add_argument(
        '-w', '--whitelabel', required=True,
        help="whitelabel name to which the import should be limited.")

    parser.add_argument(
        '-sd', '--start_date', required=True,
        help='Start date from which we replay the records.'
    )

    parser.add_argument(
        '-ed', '--end_date', default=False,
        help='End date from which we replay the records.'
    )

    parser.add_argument(
        '--api-host', required=True,
        help="hostname or address of the APIServer.")

    parser.add_argument(
        '--api-port', required=True,
        help="port for the APIServer.")

    parser.add_argument(
        '--api-use-ssl', default=False,
        help="use ssl for the APIServer.")

    parser.add_argument(
        '--recordsapi-key', required=True,
        help="APIKey for RecordsAPI.")

    parser.add_argument(
        '--mysql-api-host', required=True,
        help="hostname or address of the MySQL APIServer host.")
    parser.add_argument(
        '--mysql-api-db',
        help="Database name of APIServer. (iveventsdb)",
        default='iveventsdb')
    parser.add_argument(
        '--mysql-api-user',
        help="username of the APIServer database. Default value: %s" %
        DEFAULT_SQL_USER,
        default=DEFAULT_SQL_USER)
    parser.add_argument(
        '--mysql-api-password',
        required=True,
        help="password of the APIServer database.")

    return parser.parse_args()


class MySQLClient(object):
    def execute_query(self, query):
        try:
            cursor = self.db.cursor()
            cursor.execute(query)
            return cursor.fetchall()
        except Exception as e:
            die(str(e))

    def update_query(self, query):
        try:
            cursor = self.db.cursor()
            cursor.execute(query)
            self.db.commit()
        except Exception as e:
            die(str(e))


class APIMySQLClient(MySQLClient):
    def __init__(self, args):
        self.db = MySQLdb.connect(
            host=args.mysql_api_host,
            user=args.mysql_api_user,
            passwd=args.mysql_api_password,
            db=args.mysql_api_db,
            charset='utf8', use_unicode=False
        )
        self.whitelabel = args.whitelabel.upper()
        self.project = args.project.upper()
        self.start_date = args.start_date
        self.end_date = args.end_date
        self.project_ref = self.execute_query(
            "SELECT id FROM Projects WHERE project='%s' and whitelabel='%s'" % (
                self.project, self.whitelabel))[0][0]

    def get_record_id_list(self):
        if self.end_date:
            query = (
                "SELECT id FROM VocalRecords "
                "WHERE project_ref=%s "
                "AND start_time BETWEEN '%s' AND '%s'"
            ) % (self.project_ref, self.start_date, self.end_date)
        else:
            query = (
                "SELECT id FROM VocalRecords "
                "WHERE project_ref=%s "
                "AND start_time BETWEEN '%s' AND NOW()"
            ) % (self.project_ref, self.start_date)
        res = self.execute_query(query)
        print "-----"
        print "Get record list"
        print query + ";"
        return [r[0] for r in res]

    def set_ids_to_undeleted(self, ids):
        query = (
            "UPDATE VocalRecords "
            "SET deleted=0 "
            "WHERE id in (%s)"
        ) % (','.join([str(i) for i in ids]))
        print "-----"
        print "Set records with deleted=0"
        print query + ";"
        self.update_query(query)


def die(msg):
    print(msg)
    reactor.stop()
    sys.exit(1)


def sleep():
    return task.deferLater(reactor, 0.2, lambda: None)


@defer.inlineCallbacks
def main(args):
    mysql_client = APIMySQLClient(args)
    ids = mysql_client.get_record_id_list()
    records_client = RecordsAPIClient(
        args.recordsapi_key,
        args.api_host,
        args.api_port,
        args.api_use_ssl
    )
    if not ids:
        print 'Nothing to process.'
    else:
        print "-----"
        print "Total records to process: %s" % len(ids)
        mysql_client.set_ids_to_undeleted(ids)
        print "-----"
        print "- Processing..."
        for vocal_record_id in ids:
            try:
                yield records_client.records.create(id=vocal_record_id)
                print "Imported record [%s]" % vocal_record_id
                yield sleep()
            except Exception as e:
                die(str(e))
        print "-----"
        print "End."
    reactor.stop()


if __name__ == '__main__':
    args = parse_arguments()
    reactor.callWhenRunning(main, args)
    reactor.run()
